#source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'InsiderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inherit! :search_paths
  # Pods for InsiderDemo
  pod 'InsiderMobile'

end

target 'InsiderNotificationContent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inherit! :search_paths
  # Pods for InsiderNotificationContent
  pod "InsiderMobileAdvancedNotification"

end

target 'InsiderNotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inherit! :search_paths
  # Pods for InsiderNotificationService
  pod "InsiderMobileAdvancedNotification"

end

# Your `pod --version` have to be equal or higher than 1.8.4.
# Make sure that you have implemted `use_frameworks!` 
# Make sure that you have implemented `inherit! :search_paths`.
# Make sure that your project deployment targets equal or higher than iOS 10.0.
